export default function HomePage() {
  return (
    <main className="min-h-screen bg-dark-900">
      <nav className="fixed top-0 w-full z-50 glass"><div className="max-w-[1440px] mx-auto px-8 h-16 flex items-center justify-between"><div className="text-xl font-bold text-white">GoLuckyBD</div><div className="flex items-center gap-6">{['হোম', 'গেমস', 'লাকি হাব', 'রিওয়ার্ডস', 'VIP Club'].map((item) => (<a key={item} className="text-sm text-gray-400 hover:text-white transition-colors cursor-pointer">{item}</a>))}<button className="px-5 py-2 bg-amethyst-500 text-white rounded-xl hover:bg-amethyst-600 transition-colors">লগইন</button></div></div></nav>
      <section className="pt-32 pb-20 gradient-sovereign"><div className="max-w-[1440px] mx-auto px-8 text-center"><h1 className="text-5xl font-bold text-white mb-4">বাংলাদেশের #১ প্রিমিয়াম<br /><span className="bg-gradient-to-r from-amethyst-400 to-gold-400 bg-clip-text text-transparent">গেমিং প্ল্যাটফর্ম</span></h1><p className="text-gray-400 max-w-lg mx-auto mb-8">লটারি, ক্র্যাশ, ক্যাসিনো, স্পোর্টস বেটিং — সব এক জায়গায়। এখনই যোগ দিন!</p><div className="flex items-center justify-center gap-4"><button className="px-8 py-3 bg-amethyst-500 text-white rounded-xl glow-amethyst hover:bg-amethyst-600">এখনই শুরু করুন</button><button className="px-8 py-3 border border-dark-600 text-white rounded-xl hover:border-gray-400">ডেমো দেখুন</button></div></div></section>
      <section className="py-20 bg-dark-800"><div className="max-w-[1440px] mx-auto px-8"><h2 className="text-3xl font-bold text-white text-center mb-12">গেম ক্যাটেগরি</h2><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">{[{name:'লটারি',color:'from-purple-500 to-amethyst-500'},{name:'ক্র্যাশ',color:'from-red-500 to-orange-500'},{name:'ক্যাসিনো',color:'from-gold-500 to-gold-700'},{name:'স্লট',color:'from-blue-500 to-cyan-500'},{name:'স্পোর্টস',color:'from-green-500 to-emerald-500'},{name:'কার্ড',color:'from-amethyst-700 to-dark-600'}].map((cat) => (<div key={cat.name} className={`aspect-square rounded-2xl bg-gradient-to-br ${cat.color} flex items-center justify-center cursor-pointer hover:scale-105 transition-transform`}><span className="text-white font-semibold">{cat.name}</span></div>))}</div></div></section>
      <section className="py-16 bg-dark-900"><div className="max-w-[1440px] mx-auto px-8 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">{[{v:'১০,০০০+',l:'অ্যাক্টিভ খেলোয়াড়'},{v:'৫০+',l:'গেম সংখ্যা'},{v:'৳১ কোটি+',l:'মোট জয়'},{v:'২৪/৭',l:'সাপোর্ট'}].map((s) => (<div key={s.l}><div className="text-3xl font-bold text-gold-400">{s.v}</div><div className="text-sm text-gray-500 mt-1">{s.l}</div></div>))}</div></section>
      <footer className="py-12 bg-dark-900 border-t border-dark-700"><div className="max-w-[1440px] mx-auto px-8 text-center"><p className="text-xs text-gray-600">© 2026 GoLuckyBD. সর্বস্বত্ব সংরক্ষিত।</p></div></footer>
    </main>
  );
}
